services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    container_name: odoo-app
    user: "root" 
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ADMIN_PASSWORD=admin
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./odoo-data:/var/lib/odoo

volumes:
  odoo-db-data:
